class Music_Tracks
{
    ONL_randomMusicTracksKISKA[] = {
        "Kiska_ArrivingAtFortKiowa",
        "Kiska_CarryingGlass",
        "Kiska_CatAndMouse",
        "Kiska_ChurchDream",
        "Kiska_SpecialReport",
        "Kiska_Darkroom",
        "Kiska_MainThemeRemodel",
        "Kiska_MainThemeAtmospheric",
        "Kiska_MainTheme",
        "Kiska_TheApartment",
        "Kiska_Trust",
        "Kiska_Wanted",
        "Kiska_OutOfHorse",
        "Kiska_PowaqaRescue",
        "Kiska_Smother",
        "Kiska_Love",
        "Kiska_Gis",
        "Kiska_FirstDream",
        "Kiska_DiscoveringBuffalo",
        "Kiska_DiscoveringRiver",
        "Kiska_GoodbyeToHawk",
        "Kiska_HawkPunished",
        "Kiska_HellEnsemble",
        "Kiska_ImaginingBuffalo",
        "Kiska_KillingHawk",
        "Kiska_LookingForGlass",
        "Kiska_TheEnd",
        "Kiska_SecondDream",
        "Kiska_Rocket",
        "Kiska_Launch",
        "Kiska_Reunion"
    };

    ONL_randomMusicTracksCCM[] = {
        "CCM_SB_annasTheme",
        "CCM_PM_sentimental010",
        "CCM_PM_melancholic001",
        "CCM_PM_melancholic001_1",
        "CCM_PM_melancholic002",
        "CCM_PM_melancholic003",
        "CCM_PM_melancholic017",
        "CCM_PM_melancholic014",
        "CCM_PM_melancholic018",
        "CCM_PM_melancholic021",
        "CCM_PM_emotional004",
        "CCM_PM_emotional005",
        "CCM_PM_feelings004",
        "CCM_PM_sentimental001",
        "CCM_PM_sentimental002",
        "CCM_PM_sentimental008",
        "CCM_PM_sentimental011",
        "CCM_PM_sentimental019",
        "CCM_PM_sorrowful001",
        "CCM_PM_sorrowful004",
        "CCM_PM_sorrowful006",
        "CCM_sb_genesis",
        "CCM_sb_genesisNoMelody",
        "CCM_sb_hymn",
        "CCM_PM_thrillingAlien",
        "CCM_PM_thrilling009",
        "CCM_PM_thrilling001",
        "CCM_sb_skyward"
    };

    ONL_caveMusicTracks[] = {
        "CCM_SB_computationsAltMix",
        "CCM_SB_computations",
        "CCM_sb_theOldOnes",
        "CCM_sb_yourNumbersUp"
    };
};
